# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
# export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
# alias ls='ls $LS_OPTIONS'
# alias ll='ls $LS_OPTIONS -l'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

freecad=/mnt/build/bin/FreeCAD
alias FreeCAD="$freecad"

export HERMES_2_PATH=/mnt/build

echo "Expanding FreeCAD .bashrc for rinning FreeCAD"
echo "Command that runs FreeCad: $freecad"

#Workaround for pandas' missing bz2/lzma stuff
ln -s /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.7/lib-dynload/_bz2.cpython-37m-x86_64-linux-gnu.so
ln -s /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.7/lib-dynload/_lzma.cpython-37m-x86_64-linux-gnu.so

$freecad

